name: GLORP Integration Tests

on: [push,pull_request]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-8.0 ]
    name: ${{ matrix.smalltalk }} + ${{ matrix.rdbms }}
    steps:
      - uses: actions/checkout@v2
      - name: Install SQLite3
        run: ./scripts/install-SQLite3.sh
        env:
          RDBMS: ${{ matrix.rdbms }}
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Load Image and Run Integration Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .GLORP.ston
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RDBMS: ${{ matrix.rdbms }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{matrix.os}}-${{matrix.smalltalk}}
          token: ${{ secrets.CODECOV_TOKEN }}
